services:
  devices-db:
    image: postgres:17
    container_name: devices-db
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
    ports:
      - "5432:5432"
    networks:
      - backend

  devices-api:
    build: .
    container_name: devices-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - devices-db
    networks:
      - backend

networks:
  backend:
    driver: bridge
