services:
  db:
    image: postgres:16
    container_name: devices_db
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: devices
      POSTGRES_PASSWORD: devices
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devices -d devices"]
      interval: 5s
      timeout: 3s
      retries: 10
